### ISSUE TITLE
Undefined is not an object(RNStarPRNT.portDiscovery)

### ISSUE THREAD

**Issue by AlicanAkyol** [infoxicator/react-native-star-prnt#1]
Hello,
I want to use StarPRNT module and I tried your example function but I get the error. 

 `import { StarPRNT } from 'react-native-star-prnt';

async function portDiscovery() {
  try {
    let printers = await StarPRNT.portDiscovery('All');
    console.log(printers);
  } catch (e) {
    console.error(e);
  }
}`

**Comment by infoxicator** [comment]
Hi @AlicanAkyol sounds to me like the Native side of the plugin is not installed properly and it is not loading the native bridge, are you using Android or iOS?

**Comment by AlicanAkyol** [comment]
Thanks for replying. Firstly I want to use on Android. How do you understand cause of the error?

**Comment by infoxicator** [comment]
Hi @AlicanAkyol Try reinstalling the plugin and make sure you run `react-native link react-native-star-prnt` The android linking should happen automatically, if not let me know the version of RN and Android

**Comment by AlicanAkyol** [comment]
Hi @infoxicator . I tried it again and again but I didn't run the project.

**Comment by infoxicator** [comment]
@AlicanAkyol If this is a new project try deleting the android folder and installing again, if not try creating a brand new project and link the Plugin. Also, please let me know the version of Android and RN
