### ISSUE TITLE
After i public to App store, got rejected

### ISSUE THREAD

**Issue by lyseiha** [infoxicator/react-native-star-prnt#16]
MFi - Program Authorization.

please help

**Comment by infoxicator** [comment]
Hi @lyseiha You need to apply for a MFi code from Star [here](https://www.star-m.jp/eng/products/s_print/apple_app_mfi.html) then include that code under the notes section on your app submission on Itunes connect. I had my app approved without issue after obtaining that code 

thanks

**Comment by infoxicator** [comment]
Hi, it took a couple of days when I requested the code. Definitely quicker than apple take to review apps.

**Comment by phatlaunchdeck** [comment]
Nice, I just submitted mine as well, hopefully it'll go through quickly, our client needs the app to be live on store ASAP haha. Thanks @infoxicator

**Comment by lyseiha** [comment]
@infoxicator Thank you :)
