### ISSUE TITLE
Success but the printer not work

### ISSUE THREAD

**Issue by lyseiha** [infoxicator/react-native-star-prnt#2]
Printer not print after connect and print show console success.

**Comment by lyseiha** [comment]
![screen shot 2018-07-03 at 6 28 08 pm](https://user-images.githubusercontent.com/26889046/42217330-ebd0de1c-7eee-11e8-8a13-9b3583c97b79.png)

**Comment by infoxicator** [comment]
Hi @lyseiha please send me an example of the Array of commands you are sending to the printer
