### ISSUE TITLE
appendBitmap Android with base64 image uri - java.io.FileNotFoundException: No content provider

### ISSUE THREAD

**Issue by jeremycy** [infoxicator/react-native-star-prnt#20]
Hi there. 

When using base64 uri image string, IOS works flawlessly but on Android it was throwing java.io.FileNotFoundException: No content provider error.  

If I alter bitmap parse with decode/write bytes below it would then work.  Just wondering if this feature can be added or if I am missing something and should be handling this differently.  

Thanks!  Awesome library btw.  

```
uriString = uriString.replace("data:image/png;base64,","");
byte[] decodedString = android.util.Base64.decode(uriString, Base64.DEFAULT);
Bitmap decodedByte = android.graphics.BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);

builder.appendBitmap(decodedByte, diffusion, width, bothScale, rotation);
```

**Comment by infoxicator** [comment]
Hi @jeremycy, the appendBitmap command takes a uri not a base64 encoded string. I am surprised it works on iOS. I avoided using base64 string because of performance concerns.

**Comment by jeremycy** [comment]
@infoxicator I have a strange situation -  I am retrieving the base64 string from webview using postMessage to React Native, then try to print it.  I suppose I can also do what one user did in another thread,  use react native shot then print it that way.  Any thoughts?

Still would be nice to add support for base64 string though.  Maybe add a appendBase64String ?   :)

**Comment by jeremycy** [comment]
Closing this as not an issue, more like possible feature support.
