### ISSUE TITLE
i connect Bluetooth printer TSP100iii, but can not print

### ISSUE THREAD

**Issue by lyseiha** [infoxicator/react-native-star-prnt#25]
Please help.
The printer itself connected successfully. but the status of offline is true.
![screen shot 2019-02-06 at 12 01 33 pm](https://user-images.githubusercontent.com/26889046/52321431-4f97d900-2a07-11e9-935e-0dea4ea0f0e2.png)

**Comment by herbalifethomas** [comment]
@lyseiha  Were you able to get the TSP100iii working?
