### ISSUE TITLE
Can not print in TSP143IIIBI

### ISSUE THREAD

**Issue by lyseiha** [infoxicator/react-native-star-prnt#27]
This error occur:

Error: There was no response of the device within the timeout period.
--

{"framesToPop":1,"code":"CHECK_STATUS_ERROR","line":162306,"column":31,"sourceURL":"http://localhost:8081/index.delta?platform=android&dev=true&minify=false"}

**Comment by infoxicator** [comment]
@lyseiha I don't recommend using the connect function unless you need to query real time printer events. This shouldn't happen when printing directly using the print() function passing the portName on every call
