### ISSUE TITLE
Only PartialCutWithFeed works with TSP100IIIW

### ISSUE THREAD

**Issue by bosung90** [infoxicator/react-native-star-prnt#28]
I was able to connect to the printer and send a print command.

However, every print only comes out with tiny little slip with partial cut.

    async function portDiscovery() {
      try {
        let printers = await StarPRNT.portDiscovery('All')
        console.log(printers)
        if (printers && printers.length > 0) {
          await connect(printers[0].portName)
          portName = printers[0].portName
          await new Promise(r => setTimeout(r, 5000))
          let commands = []
          commands.push({ append: 'Star Clothing Boutique\n' + '123 Star Road\n' + 'City, State 12345\n' + '\n' })
          commands.push({ appendRawBytes: [0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x2e] })
          commands.push({ appendRaw: 'Star Clothing Boutique\n' + '123 Star Road\n' + 'City, State 12345\n' + '\n' })
          commands.push({ appendUnderline: 'Star Clothing Boutique\n' + '123 Star Road\n' + 'City, State 12345\n' + '\n' })
          commands.push({ appendAbsolutePosition: 40, data: 'Text with absolute position' })
          commands.push({ appendCutPaper: StarPRNT.CutPaperAction.PartialCutWithFeed })
          commands.push({ appendRaw: 'Star Clothing Boutique\n' + '123 Star Road\n' + 'City, State 12345\n' + '\n' })
          commands.push({ appendRaw: 'Star Clothing Boutique\n' + '123 Star Road\n' + 'City, State 12345\n' + '\n' })
          commands.push({ appendRaw: 'Star Clothing Boutique\n' + '123 Star Road\n' + 'City, State 12345\n' + '\n' })

          print(commands, printers[0].portName)
        }
      } catch (e) {
        console.error(e)
      }
    }

this is my connect function

    async function connect(portName, emulation = StarPRNT.Emulation.StarGraphic, hasBarcodeReader = false) {
      try {
        var connect = await StarPRNT.connect(portName, emulation, hasBarcodeReader)
        console.log(connect) // Printer Connected!
      } catch (e) {
        console.error(e)
      }
    }

and print function

    async function print(commands, portName, emulation = StarPRNT.Emulation.StarGraphic) {
      try {
        var printResult = await StarPRNT.print(emulation, commands, portName)
        console.log(printResult) // Success!
      } catch (e) {
        console.error(e)
      }
    }

**Comment by cstudios-slovakia** [comment]
So...that is a raster printer. You need to convert your text into bitmap before you can print that out. 
P.S.: You will need the StarGraphic emulation

**Comment by bosung90** [comment]
@cstudios-slovakia Thank you so much for your answer. I am planning to use it only on Android. I was wondering if this library is capable of converting text into bitmap without having to touch the native code. Thank you so much!!

**Comment by aysfzaicmu** [comment]
@bosung90 i'm in the same situation. so did you end up using a command in this package to convert to bitmap?

**Comment by bosung90** [comment]
@aysfzaicmu no I haven't had a chance to get it to work yet

**Comment by ararog** [comment]
@bosung90 @aysfzaicmu please give a try on `appendBitmapText` command, this command worked for me.

**Comment by lukhol** [comment]
@ararog appendBitmapText works only on iOS, implementation is missing on Android

**Comment by HunWalk** [comment]
we have a custom fork here https://github.com/cstudios-slovakia/react-native-star-prnt
You can use the appendRasterText command. This works both on android and ios, tested with actual printers

**Comment by stefangeorg** [comment]
anyone else getting "Fail to open Port", for the BT:TSP100. I've tried the print with portName and without parameter. Connect says it worked, check status says connected but print says Fail to open Port
let commands = [];
      commands.push({
        appendBitmapText:
          "Star Clothing Boutique\n" +
          "123 Star Road\n" +
          "City, State 12345\n" +
          "\n"
      });
      commands.push({ appendBitmap: image });
 try {
        //this.connect()
        
        const result = await StarPRNT.print(this.emulation, commands, this.port);
        alert('printed')
      } catch(e) {
        alert(JSON.stringify(e))
        bugsnag.notify(e)
      }

**Comment by HunWalk** [comment]
Make sure the printer does not have harware error. Empty paper, paper cutter misaligned. If its hardware error you should see a blinking red light, but you can listen to hardware events by attaching a listener, but for this you have to use StarPRNT.connect first, then you will be able to console log them out. But either way it should work.

**Comment by stefangeorg** [comment]
@HunWalk thanks for the response. printer is working fine if I use the Star Print app they supply, it prints. From the docs I don't see how one would listen to the events?

**Comment by stefangeorg** [comment]
@HunWalk  I'm getting from status receiptPaperEmpty: true, its definitely full. and works when using their app

**Comment by stefangeorg** [comment]
@HunWalk i started a fresh project and can get it to print QR codes and barcodes. I'm now working on appendBitmap, but its not working

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Image} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});
import { StarPRNT } from 'react-native-star-prnt';
import { Button } from 'react-native-elements';
import ViewShot, { releaseCapture } from "react-native-view-shot";

async function portDiscovery() {
  try {
    let printers = await StarPRNT.portDiscovery('All');
    console.warn(printers);
  } catch (e) {
    console.error(e);
  }
}
let refValue;
type Props = {};
export default class App extends Component<Props> {
  constructor() {    
    
    super()
    this.state = {
      image: null
    }
    this.print = this.print.bind();
  }

  onCapture = uri => {
    console.warn("do something with ", uri);
    ///this.print(uri)
    this.setState({ 'image': uri })
    
  }
  print = async () => {
   
    try {
      let commands = [];
      commands.push({ appendBitmap: this.state.image});
      
      //commands.push({ appendQrCode: "{BStar", QrCodeModel: "No2", QrCodeLevel: "H", cell: 20, alignment: "Center" });
      //commands.push({ appendBarcode: "{BThis is Beautifule", BarcodeSymbology: "Code128", BarcodeWidth: "Mode2", height: 100, hri: true });
      
      console.warn(commands)
      var printResult = await StarPRNT.print('StarGraphic', commands, 'BT:TSP100');
      console.warn(printResult); // Success!
    } catch (e) {
      console.warn(e);
    }
  }
  render() {
    //portDiscovery();
    return (
      <View >
        <Text>{this.state.image}</Text>
        {this.state.image ? (
          <Image
            style={{ width: 150, height: 50 }}
            source={{uri : this.state.image}}
          />
         ) : null }
        <ViewShot onCapture={this.onCapture} captureMode="mount" options={{  'format': 'png'}}>
          <View class="title"><Text>Name</Text></View>
          <View class="title" ><Text>Recipient 123</Text></View>
          <View class="sub_title"><Text>Address: Address blah blah</Text></View>
          <View class="sub_title"><Text>Tel: 012 333 44</Text></View>
          <View class="sub_title"><Text>addres: Nono</Text></View>
          <View class="room_info"><Text>asd: 123</Text></View>
          <View class="sub_title"><Text>Invoice No: 1234</Text></View>
        </ViewShot>
        <Button onPress={this.print} title="Print"/>
        
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
`

**Comment by HunWalk** [comment]
I commented something useful above:

> we have a custom fork here https://github.com/cstudios-slovakia/react-native-star-prnt
> You can use the appendRasterText command. This works both on android and ios, tested with actual printers

There is no documentation, but here is a piece of code that works

```javascript
makeBitmap = (base64) => {
        if (Platform.OS === 'ios') {
            return { appendBitmap: base64, diffusion: true, width: 320, bothScale: true, absolutePosition: (590-320)/2 }
        }else{
            return { 
                appendBase64Bitmap: base64.replace(/^data:image\/[a-z]+;base64,/, ""), 
                diffusion: true, 
                width: 400, 
                bothScale: true, 
                absolutePosition: (590 - 320) / 2
            }
        }
        
    }
```

**Comment by stefangeorg** [comment]
@HunWalk 

I fixed it with:

`commands.push({ appendBitmap: `file:${image}` });`

So now it works in my limited demo app... still no luck in the real app though.

**Comment by HunWalk** [comment]
@stefangeorg double check the emulation, but please try to solve it alone, use google or think before spamming comments under a github issue which was not opened for this case.

@infoxicator please close this issue, it's already going in a different direction. If you do not intend to maintain this repo please let me know.

Cheers

**Comment by infoxicator** [comment]
@HunWalk I can give you access to the repository and now if you want to help maintain it?

**Comment by HunWalk** [comment]
@infoxicator yepp, i could check the issues on this repo every week in order to patch some things up by sending a PR, but the first thing this repo really needs is some additional informations inside the docs, because people are too lazy to read the manuals of the devices.
I'm gonna send a PR for this purpose.
I don't really think I need access, unless you want to abandon this repo, or you really don't have time to maintain it.

**Comment by infoxicator** [comment]
I could do with some help specially publishing new versions to non I left the company I developed this plugin for and don’t have access to printers to test. I can add you as a contributor

**Comment by HunWalk** [comment]
Okay then, we have an mPop an L200 and a Paypoint for ipad device in here i can use for testing. 
You can reach me at gergely@cstudios.ninja for further communications
