### ISSUE TITLE
Supporting emulation of any STAR printer(in documentation list)

### ISSUE THREAD

**Issue by aysfzaicmu** [infoxicator/react-native-star-prnt#30]
In order to give the flexibility of connecting to any Star printer, whether the emulation is StarPRNT or StarGraphic or ESCPOS, we would need to be able to get a model's emulation from a function like portDiscovery or connect where we can get the emulation of a specific model and accordingly input a bitmap or string to the specific printer. It does not seem like we are getting the emulation from these functions so how would do support different star printer models?

**Comment by infoxicator** [comment]
Hi @aysfzaicmu take a look at the StarSDK documentation, you will find the printer list and their emulation as well as what commands are supported by each printer/emulation. After finding out what emulation your printer uses, then just pass it as a parameter to the connect or print commands as described on the documentation of this plugin
