### ISSUE TITLE
Can't print bitmap and barcode on the same line

### ISSUE THREAD

**Issue by AngeloMateus** [infoxicator/react-native-star-prnt#39]
I know the SDK allows it because the sample prints from the SDK app do it.
I'm trying to print a barcode with a bitmap image side by side but every append command starts in a newline and I'm not sure how to use appendBitmap and appendBarcode with appendMultiple.

           commands.push({ appendCutPaper: 'PartialCut'});
           commands.push({
                appendBarcode: "{B" + '88712365444',
                BarcodeSymbology: 'Code128',
                BarcodeWidth: 'Mode1',
                height: 100,
                hri: true,
            });
            commands.push({
                appendBitmap: logo.data,
                width: 100,
                bothScale: true,
                diffusion: true,
            });

![IMG_2047](https://user-images.githubusercontent.com/34476066/60274482-05e55780-98f0-11e9-9c46-0c494f20fc06.jpeg)

**Comment by infoxicator** [comment]
I think I faced this issue before but couldn’t find a workaround. Might need someone to look into it maybe try again to see if it is possible

**Comment by HunWalk** [comment]
Barcodes on receipts should be standardized. You shouldn't use any artwork at the same line, because cheaper readers can find it distracting.
However i will look into it later.
