### ISSUE TITLE
TSP100 can not print anything, it will only cut paper...

### ISSUE THREAD

**Issue by wgltony** [infoxicator/react-native-star-prnt#45]
Can't figure out what causes the problem. The result shows success, but it will only do cut paper action, nothing will be printed.

Please help! Both IOS & Android are the same.

{result: true, title: "Send Commands", message: "Success"} 

print = async(emulation, commands, portName)=> {
        //await this.portDiscovery();
        //await this.connect(portName, emulation, false);

        try {
          var printResult = await StarPRNT.print(emulation, commands, portName);
          console.log(printResult); // Success!
        } catch (e) {
          console.log(e);
        }
}

  printReceipt = ()=>{
    let commandsArray = [];
    // commandsArray.push({appendInternational: 'USA'});
    // commandsArray.push({appendEncoding: 'GB2312'});
    // commandsArray.push({appendFontStyle: 'A'});
    // commandsArray.push({appendMultiple:" $156.95\n", width:2, height:2});
    // commandsArray.push({append:" $156.95. test test test\n"});
    // commandsArray.push({appendAlignment: 'Left'});
    
    commandsArray.push({append:" $156.95. test test test\n"});
    commandsArray.push({append:
        "Star Clothing Boutique\n" +
        "123 Star Road\n" +
        "City, State 12345\n" +
        "\n"});
    commandsArray.push({appendCutPaper: StarPRNT.CutPaperAction.FullCutWithFeed});

    this.print('StarGraphic', commandsArray, 'TCP:192.168.1.24');
  }

**Comment by wgltony** [comment]
I have tried to reset the printer, and nothing changes.

**Comment by infoxicator** [comment]
Please check the Star documentation and verify you are using the correct emulation for your printer. If I recall correctly StarGraphic is not the emulation for the TSP100

**Comment by infoxicator** [comment]
I see. So basically the TSP100 can only print images which means that most of the commands sent through the ‘print’ command won’t work. The only way you can use it is by printing raster receipts

**Comment by wgltony** [comment]
Thank you so much. Problem solved. Command "appendBitmap" Works perfectly. I just need to create image base receipts now.

**Comment by wgltony** [comment]
Hi infoxicator, I have managed to make my ios app works perfectly. However, the same code do not work on my Android app, I have no idea why, and console only shows printer success, but actually nothing will be printed, it will only cut a small piece of paper. 

I have checked the image path is valid and it works on IOS. Do you have any idea why it is not working on Android? Thanks

![image](https://user-images.githubusercontent.com/12904760/64193683-3d6e0400-ce4b-11e9-9321-69f22c64ebff.png)

**Comment by wgltony** [comment]
Ok, I get it solved. :) Changed a little bit in RNStarPrntModule.java, Now we can print directly from image URL.   

![image](https://user-images.githubusercontent.com/12904760/64198331-094c1080-ce56-11e9-9e0b-9fac03c650d6.png)

![image](https://user-images.githubusercontent.com/12904760/64198424-33053780-ce56-11e9-9337-e82a1e17ab4e.png)
