### ISSUE TITLE
Star Print in SM230i appendBitmap not print anything

### ISSUE THREAD

**Issue by Andonium500** [infoxicator/react-native-star-prnt#54]
Hi, 

I try to print image in printer Star SM-230i but de appendBitmap not print anything. I try different configurations but nothing...

I use a uri base64 to print the image? 

Someone can explain me how i can print it? 

My code:

  commandsArray.push({
    appendBitmap: sign,
    width: 100,
    rotation: StarPRNT.BitmapConverterRotation.Normal
  });

thanks

Andoni

**Comment by infoxicator** [comment]
Try first passing the file uri of the image stored on the phone. I don’t think base64 is fully supported.  Someone tried to add it to the ionic version of it but don’t think it has been implemented on this lib
